# Generated by Django 3.2.25 on 2024-04-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, default='app.logomakr.com/3EC6KR', max_length=6000, null=True),
        ),
    ]
